#!/bin/sh
#
# Description: A cli bookmark manager written in POSIX shell
#
# Author: NRK

##########
# CONFIG #
##########

# Where all the data gets stored
# Respects XDG_DATA_HOME if set
[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME="$HOME/.local/share"
DATA_DIR="${XDG_DATA_HOME}/sxbm"

# Colors
# For a list of ANSI color codes, check the link below
# https://gist.github.com/Prakasaka/219fe5695beeb4d6311583e79933a009
COL_LINK="\033[1;31m"     # Red
COL_TITLE="\033[1;33m"    # Yellow
COL_LINE_NUM="\033[1;34m" # Blue

# 1 to enable encryption, 0 to disable it
ENCRYPTION="0"

# Auto fetch title. 1 to enable, 0 to disable
TITLE_FETCH="1"

die(){
  [ -z "$1" ] ||
    printf "$@\n" > /dev/stderr
  exit 1
}

usage(){
  printf "Usage: sxbm <command> [<args>]\n"
  printf "
COMMANDS:
    add           <link> [title] [+tags]
    ls|list       [-c|--disable-colors] [title] [+tags]
    open          [-f|--force] <line_num|title|+tags>
    rm|remove     [-f|--force] <line_num|title|+tags>
    edit          [line_num|title|+tags]
    -h|--help     print this text and exit
    -v|--version  print the version and exit\n\n"
}

[ -z "$1" ] && usage && die

case "$1" in
  "add")
    ;;
  "ls"|"list")
    ;;
  "open")
    ;;
  "rm"|"remove")
    ;;
  "edit")
    ;;
  "-h"|"--help")
    usage && die
    ;;
  "-v"|"--version")
    ;;
  *)
    die "Invalid command. Use 'sxbm -h' for help!"
    ;;
esac
